/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.login.admin;

import GUI.login.LoginPage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class AdminLog extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminLog.class.getName());

    /**
     * Creates new form AdminPage
     */
    public AdminLog() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usnFilAdmin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passFilAdmin = new javax.swing.JPasswordField();
        kembaliBut = new javax.swing.JButton();
        masukBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("ADMIN");

        jLabel2.setText("Username:");

        usnFilAdmin.addActionListener(this::usnFilAdminActionPerformed);

        jLabel3.setText("Password:");

        passFilAdmin.addActionListener(this::passFilAdminActionPerformed);

        kembaliBut.setText("Kembali");
        kembaliBut.addActionListener(this::kembaliButActionPerformed);

        masukBut.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        masukBut.setText("Masuk");
        masukBut.addActionListener(this::masukButActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(kembaliBut, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usnFilAdmin)
                            .addComponent(passFilAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(masukBut, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usnFilAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passFilAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(masukBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(kembaliBut)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masukButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukButActionPerformed
        String username = usnFilAdmin.getText();
        String password = new String(passFilAdmin.getPassword()); 

        // 2. Validasi jika form kosong
        if (username.trim().isEmpty() || password.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Username dan Password tidak boleh kosong!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Hentikan proses jika kosong
        }

        // 3. BENTUK OBJEK ADMIN
        // Parameter: idUser, username, password, tingkatAkses
        // ID dan tingkatAkses bisa dikosongkan/diisi default sementara karena 
        // database hanya butuh username, password, dan role untuk login.
        UserPackage.Admin adminUser = new UserPackage.Admin("", username, password, "SuperAdmin");

        // 4. Panggil class UserLogin untuk cek database
        Database.UserLogin prosesLogin = new Database.UserLogin();
        
        // Cek login menggunakan objek adminUser. 
        // Method ini akan otomatis mengambil .getRole() yang bernilai "Admin".
        boolean isSuccess = prosesLogin.loginUser(adminUser);

        // 5. Logika if-else penentuan hasil login
        if (isSuccess) {
            // JIKA BENAR: Masuk ke AdminHome
            javax.swing.JOptionPane.showMessageDialog(this, "Login Berhasil! Selamat datang Admin.", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            AdminHome adminHome = new AdminHome();
            adminHome.setVisible(true);
            this.dispose(); // Tutup halaman login

        } else {
            // JIKA SALAH: Muncul notif usn/pw/role salah
            javax.swing.JOptionPane.showMessageDialog(this, "Login Gagal! Username, Password salah, atau Anda bukan Admin.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);

            // Reset isian field
            usnFilAdmin.setText("");   
            passFilAdmin.setText("");  
            usnFilAdmin.requestFocus(); // Kembalikan kursor ke kolom username
        }
    }//GEN-LAST:event_masukButActionPerformed

        private void usnFilAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usnFilAdminActionPerformed
            String username = usnFilAdmin.getText();

        // Validasi input awal menggunakan if-else
        if (username.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Username tidak boleh kosong!");
        } else {
            try {
                // Koneksi ke database
                String url = "jdbc:mysql://localhost:3306/db_buanacoffee";
                java.sql.Connection conn = java.sql.DriverManager.getConnection(url, "root", "");

                // Query untuk cek username
                String sql = "SELECT * FROM tabel_admin WHERE username = ?";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, username);
                java.sql.ResultSet rs = pst.executeQuery();

                // Logika if-else untuk hasil database
                if (rs.next()) {
                    // Jika username ditemukan, pindah ke kolom password
                    passFilAdmin.requestFocus();
                } else {
                    // Jika tidak ditemukan
                    javax.swing.JOptionPane.showMessageDialog(this, "Username tidak terdaftar!");
                    usnFilAdmin.setText("");
                }

                conn.close();
            } catch (java.sql.SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_usnFilAdminActionPerformed

    private void passFilAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFilAdminActionPerformed
        String username = usnFilAdmin.getText();
    String password = new String(passFilAdmin.getPassword());
    
    // Validasi input awal menggunakan if-else
    if (username.trim().isEmpty() || password.trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Username dan Password harus diisi!");
    } else {
        try {
            // Koneksi ke database
            String url = "jdbc:mysql://localhost:3306/nama_database_anda";
            java.sql.Connection conn = java.sql.DriverManager.getConnection(url, "root", "");
            
            // Query cek username DAN password sekaligus
            String sql = "SELECT * FROM users WHERE username = ? AND password = ?";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, username);
            pst.setString(2, password);
            java.sql.ResultSet rs = pst.executeQuery();
            
            // Logika if-else untuk validasi login
            if (rs.next()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Login Berhasil!");
                
                // TODO: Buka halaman utama aplikasi Anda di sini
                // Contoh: new HalamanUtama().setVisible(true); this.dispose();
                
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Password salah!");
                passFilAdmin.setText("");
                passFilAdmin.requestFocus();
            }
            
            
            conn.close();
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_passFilAdminActionPerformed

    private void kembaliButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliButActionPerformed
        LoginPage login = new LoginPage();
        login.setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_kembaliButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminLog().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton kembaliBut;
    private javax.swing.JButton masukBut;
    private javax.swing.JPasswordField passFilAdmin;
    private javax.swing.JTextField usnFilAdmin;
    // End of variables declaration//GEN-END:variables
}
