/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.login.admin;

/**
 *
 * @author Axioo Pongo
 */
public class KelolaUangPage extends javax.swing.JFrame {

    /**
     * Creates new form KelolaUangPage
     */
    public KelolaUangPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idFil = new javax.swing.JTextField();
        namaMenu = new javax.swing.JTextField();
        hargaMenu = new javax.swing.JTextField();
        simpanBut = new javax.swing.JButton();
        kembaliBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Kelola Menu");

        jLabel2.setText("Masukan ID menu:");

        jLabel3.setText("Nama menu baru:");

        jLabel4.setText("Harga menu baru:");

        idFil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFilActionPerformed(evt);
            }
        });

        namaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaMenuActionPerformed(evt);
            }
        });

        hargaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaMenuActionPerformed(evt);
            }
        });

        simpanBut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        simpanBut.setText("Simpan");
        simpanBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButActionPerformed(evt);
            }
        });

        kembaliBut.setText("Kembali");
        kembaliBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idFil, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(namaMenu)
                            .addComponent(hargaMenu)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(simpanBut, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kembaliBut, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idFil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hargaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(simpanBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(kembaliBut)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButActionPerformed
        String idMenu = idFil.getText();
        String namaM = namaMenu.getText();
        String hargaM = hargaMenu.getText();
        
        if (idMenu.trim().isEmpty() || namaM.trim().isEmpty() || hargaM.trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Semua data (ID, Nama, Harga) harus diisi!");
    } else {
        try {
            // 3. Ubah tipe data ID dan Harga dari String menjadi Integer (Angka)
            int id = Integer.parseInt(idMenu);
            int harga = Integer.parseInt(hargaM);

            // 4. Koneksi ke Database db_buanacoffee
            String url = "jdbc:mysql://localhost:3306/db_buanacoffee";
            String userDB = "root";
            String passDB = ""; 
            java.sql.Connection conn = java.sql.DriverManager.getConnection(url, userDB, passDB);
            
            // 5. Query SQL untuk menambahkan data (INSERT)
            String sql = "INSERT INTO menu (id, nama, harga) VALUES (?, ?, ?)";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            
            // Memasukkan nilai ke dalam tanda tanya (?) pada query
            pst.setInt(1, id);
            pst.setString(2, namaM);
            pst.setInt(3, harga);
            
            // 6. Eksekusi query untuk menyimpan ke database
            pst.executeUpdate(); // Gunakan executeUpdate() untuk INSERT, UPDATE, DELETE
            
            javax.swing.JOptionPane.showMessageDialog(this, "Data menu berhasil disimpan!");
            
            // 7. Reset isian textfield agar kembali kosong setelah berhasil disimpan
            idFil.setText("");
            namaMenu.setText("");
            hargaMenu.setText("");
            idFil.requestFocus(); // Kembalikan kursor ke kolom ID
            
            // Tutup koneksi
            pst.close();
            conn.close();
            
        } catch (NumberFormatException e) {
            // Menangkap error jika user memasukkan huruf pada kolom ID atau Harga
            javax.swing.JOptionPane.showMessageDialog(this, "ID dan Harga harus berupa ANGKA!");
        } catch (java.sql.SQLException e) {
            // Menangkap error database (misal: ID sudah ada/duplikat)
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan data! Error: " + e.getMessage());
        }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_simpanButActionPerformed
    
    private void kembaliButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliButActionPerformed
        AdminHome adHome = new AdminHome();
        adHome.setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_kembaliButActionPerformed

    private void hargaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaMenuActionPerformed

    private void namaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaMenuActionPerformed

    private void idFilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFilActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KelolaUangPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KelolaUangPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KelolaUangPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KelolaUangPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KelolaUangPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hargaMenu;
    private javax.swing.JTextField idFil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton kembaliBut;
    private javax.swing.JTextField namaMenu;
    private javax.swing.JButton simpanBut;
    // End of variables declaration//GEN-END:variables
}
