/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.login.admin;

/**
 *
 * @author lenovo
 */
public class KelolaPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KelolaPage.class.getName());

    /**
     * Creates new form KelolaPage
     */
    public KelolaPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idFil = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        simpanBut = new javax.swing.JButton();
        kembaliBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Kelola Menu");

        jLabel2.setText("Masukan ID Menu");

        idFil.addActionListener(this::idFilActionPerformed);

        jLabel3.setText("Nama menu baru:");

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jLabel4.setText("Harga menu baru:");

        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        simpanBut.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        simpanBut.setText("Simpan");
        simpanBut.addActionListener(this::simpanButActionPerformed);

        kembaliBut.setText("Kembali");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(simpanBut, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(idFil, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(jTextField1)))
                    .addComponent(kembaliBut, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idFil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(simpanBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(kembaliBut))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idFilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFilActionPerformed
        
    }//GEN-LAST:event_idFilActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void simpanButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButActionPerformed
        String idMenu = idFil.getText();
    String namaMenu = jTextField1.getText();
    String hargaMenu = jTextField2.getText();

    // 2. Validasi apakah ada kolom yang dibiarkan kosong
    if (idMenu.trim().isEmpty() || namaMenu.trim().isEmpty() || hargaMenu.trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Semua data (ID, Nama, Harga) harus diisi!");
    } else {
        try {
            // 3. Ubah tipe data ID dan Harga dari String menjadi Integer (Angka)
            int id = Integer.parseInt(idMenu);
            int harga = Integer.parseInt(hargaMenu);

            // 4. Koneksi ke Database db_buanacoffee
            String url = "jdbc:mysql://localhost:3306/db_buanacoffee";
            String userDB = "root";
            String passDB = ""; 
            java.sql.Connection conn = java.sql.DriverManager.getConnection(url, userDB, passDB);
            
            // 5. Query SQL untuk menambahkan data (INSERT)
            String sql = "INSERT INTO menu (id, nama, harga) VALUES (?, ?, ?)";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            
            // Memasukkan nilai ke dalam tanda tanya (?) pada query
            pst.setInt(1, id);
            pst.setString(2, namaMenu);
            pst.setInt(3, harga);
            
            // 6. Eksekusi query untuk menyimpan ke database
            pst.executeUpdate(); // Gunakan executeUpdate() untuk INSERT, UPDATE, DELETE
            
            javax.swing.JOptionPane.showMessageDialog(this, "Data menu berhasil disimpan!");
            
            // 7. Reset isian textfield agar kembali kosong setelah berhasil disimpan
            idFil.setText("");
            jTextField1.setText("");
            jTextField2.setText("");
            idFil.requestFocus(); // Kembalikan kursor ke kolom ID
            
            // Tutup koneksi
            pst.close();
            conn.close();
            
        } catch (NumberFormatException e) {
            // Menangkap error jika user memasukkan huruf pada kolom ID atau Harga
            javax.swing.JOptionPane.showMessageDialog(this, "ID dan Harga harus berupa ANGKA!");
        } catch (java.sql.SQLException e) {
            // Menangkap error database (misal: ID sudah ada/duplikat)
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan data! Error: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_simpanButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KelolaPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idFil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton kembaliBut;
    private javax.swing.JButton simpanBut;
    // End of variables declaration//GEN-END:variables
}
