/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.login.pelanggan;
import GUI.login.LoginPage;

/**
 *
 * @author lenovo
 */
public class PelangganLog extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PelangganLog.class.getName());

    /**
     * Creates new form PelangganPage
     */
    public PelangganLog() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usnFilPel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passFilPel = new javax.swing.JPasswordField();
        masukButPel = new javax.swing.JButton();
        kembaliBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("PELANGGAN");

        jLabel2.setText("Username:");

        usnFilPel.addActionListener(this::usnFilPelActionPerformed);

        jLabel3.setText("Password:");

        passFilPel.addActionListener(this::passFilPelActionPerformed);

        masukButPel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        masukButPel.setText("Masuk");
        masukButPel.addActionListener(this::masukButPelActionPerformed);

        kembaliBut.setText("Kembali");
        kembaliBut.addActionListener(this::kembaliButActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usnFilPel)
                            .addComponent(passFilPel, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(masukButPel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kembaliBut, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usnFilPel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passFilPel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(masukButPel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(kembaliBut)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masukButPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukButPelActionPerformed
        // 1. Ambil inputan dari GUI
        String username = usnFilPel.getText();
        String password = new String(passFilPel.getPassword()); 

        // 2. Validasi jika form kosong
        if (username.trim().isEmpty() || password.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Username dan Password tidak boleh kosong!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Hentikan proses jika kosong
        }

        // 3. BENTUK OBJEK PELANGGAN
        // Parameter: idUser, username, password, poinMember
        // ID dikosongkan (""), poinMember diset 0 sementara karena database 
        // hanya butuh username, password, dan role untuk verifikasi login.
        UserPackage.Pelanggan pelangganUser = new UserPackage.Pelanggan("", username, password, 0);

        // 4. Panggil class UserLogin untuk cek database
        Database.UserLogin prosesLogin = new Database.UserLogin();
        
        // Cek login menggunakan objek pelangganUser. 
        // Method ini otomatis memanggil getRole() yang bernilai "Pelanggan".
        boolean isSuccess = prosesLogin.loginUser(pelangganUser);

        // 5. Logika if-else penentuan hasil login
        if (isSuccess) {
            // JIKA BENAR: Masuk ke halaman Home Pelanggan
            javax.swing.JOptionPane.showMessageDialog(this, "Login Berhasil! Selamat datang, " + username + ".", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            PelangganHome pelHome = new PelangganHome(username);
            pelHome.setVisible(true);
            this.dispose();
            // TODO: Buka halaman utama Pelanggan (Pastikan class PelangganHome sudah dibuat)
            // PelangganHome home = new PelangganHome();
            // home.setVisible(true);
            
            this.dispose(); // Tutup halaman login

        } else {
            // JIKA SALAH: Muncul notif usn/pw/role salah
            javax.swing.JOptionPane.showMessageDialog(this, "Login Gagal! Username, Password salah, atau Anda bukan Pelanggan.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);

            // Reset isian field
            usnFilPel.setText("");   
            passFilPel.setText("");  
            usnFilPel.requestFocus(); // Kembalikan kursor ke kolom username
        }
    }//GEN-LAST:event_masukButPelActionPerformed

    private void kembaliButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliButActionPerformed
        LoginPage login = new LoginPage();
        login.setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_kembaliButActionPerformed

    private void usnFilPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usnFilPelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usnFilPelActionPerformed

    private void passFilPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFilPelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFilPelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PelangganLog().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton kembaliBut;
    private javax.swing.JButton masukButPel;
    private javax.swing.JPasswordField passFilPel;
    private javax.swing.JTextField usnFilPel;
    // End of variables declaration//GEN-END:variables
}
