/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lenovo
 */
public class LandingPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LandingPage.class.getName());

    /**
     * Creates new form LandingPage
     */
    public LandingPage() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tittle = new javax.swing.JLabel();
        registBut = new javax.swing.JButton();
        loginBut = new javax.swing.JButton();
        keluarBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        tittle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tittle.setText("APLIKASI BUANA COFFEE");

        registBut.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        registBut.setText("REGIST");
        registBut.addActionListener(this::registButActionPerformed);

        loginBut.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        loginBut.setText("LOGIN");
        loginBut.addActionListener(this::loginButActionPerformed);

        keluarBut.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        keluarBut.setText("Keluar");
        keluarBut.addActionListener(this::keluarButActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tittle)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(registBut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loginBut))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(keluarBut)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(tittle)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registBut)
                    .addComponent(loginBut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(keluarBut)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButActionPerformed
        LoginPage login = new LoginPage();
        login.setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_loginButActionPerformed

    private void registButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registButActionPerformed
        RegistPage regist = new RegistPage();
        regist.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_registButActionPerformed

    private void keluarButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarButActionPerformed
        System.exit(0);
// TODO add your handling code here:
    }//GEN-LAST:event_keluarButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LandingPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton keluarBut;
    private javax.swing.JButton loginBut;
    private javax.swing.JButton registBut;
    private javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables
}
